Aditya - Changing cell node initializing value from Nan to data index
OmicsML/dance pull request #146
Opened 2023-01-21 20:09 UTC by adiark

NaN's were passed to initialize cell node parameter to build the graph, changed to index value 

graph.ndata['label'] = torch.tensor([-1] * num_genes + list(np.arange(len(X))))

2023-01-23 15:58 UTC, RemyLau commented
Thanks for your contribution @adiark! Could you elaborate a little more on the reason for this change? Does this cause an error in one of the examples scripts you are running? If so, could you provide some more context about the error it caused and how this change fixes that particular error?

2023-01-23 16:00 UTC, RemyLau commented
Since @WenzhuoTang worked on this module before, I'll also involve him in this thread.

2023-01-23 22:41 UTC, adiark commented
Sure Remy. As per my understanding, on running the code graphsc.py with any example dataset, the function cell_gene_graph() was creating a graph with NAN values assigned in graph.ndata['label'] feature. So when training ID's where fetch (train_ids = np.where(labels != -1)[0]) to pass into  dgl.dataloading.NodeDataLoader() function only NaN's where passed resulting in NoneType error. Changing graph.ndata['label'] = torch.tensor([-1] * num_genes + np.nan*len(x)) to graph.ndata['label'] = torch.tensor([-1] * num_genes + list(np.arange(len(X)))), results in adding row index at the end of the tensor. Therefore, train_ids will fetch the row index to pass into NodeDataLoader function, result in creating dataloader with right trainingID's

2023-01-24 00:56 UTC, RemyLau requested changes
Thanks for the explanation. Please remove the commented part `#[np.nan]...` from the code base. Otherwise, it LGTM.

2023-01-24 00:56 UTC, RemyLau commented on dance/transforms/graph_construct.py
> +    graph.ndata['label'] = torch.tensor([-1] * num_genes + list(np.arange(len(X))))  #[np.nan] * len(X))
```suggestion
    graph.ndata['label'] = torch.tensor([-1] * num_genes + list(np.arange(len(X))))
```

2023-01-24 01:03 UTC, RemyLau approved these changes

2023-01-24 01:03 UTC, merged

2023-01-24 01:05 UTC, adiark commented on dance/transforms/graph_construct.py
> +    graph.ndata['label'] = torch.tensor([-1] * num_genes + list(np.arange(len(X))))  #[np.nan] * len(X))
Okay, Thank you for the review.